"""Tests for coordinate-file import and export.

The stakes here are higher than they look. A mis-detected ordering produces an
airfoil that is upside down or inside out, and the panel methods will solve it
without complaint and return a confident wrong answer. So the tests cover not
only that valid files are read correctly, but that ambiguous and inconsistent
ones are *refused* rather than resolved by guessing.

Fixture files are written out by hand in the style of published coordinate sets
rather than generated by ``write_dat``, so that a round-trip test cannot pass
merely because the reader and writer share a bug.
"""

from __future__ import annotations

import numpy as np
import pytest

from aerolab.exceptions import GeometryError
from aerolab.geometry.dat_io import parse_dat, read_dat, write_dat
from aerolab.geometry.naca import naca

# A coarse but genuine NACA 0012, written the way Selig files are published:
# name line, then one loop from the trailing edge over the top and back.
SELIG_TEXT = """NACA 0012 COARSE
  1.000000   0.001260
  0.750000   0.028869
  0.500000   0.052940
  0.250000   0.062594
  0.100000   0.047383
  0.025000   0.026877
  0.000000   0.000000
  0.025000  -0.026877
  0.100000  -0.047383
  0.250000  -0.062594
  0.500000  -0.052940
  0.750000  -0.028869
  1.000000  -0.001260
"""

# The same section in Lednicer form: count header, then upper then lower, each
# running from the leading edge aft.
LEDNICER_TEXT = """NACA 0012 COARSE
       7.        7.

  0.000000   0.000000
  0.025000   0.026877
  0.100000   0.047383
  0.250000   0.062594
  0.500000   0.052940
  0.750000   0.028869
  1.000000   0.001260

  0.000000   0.000000
  0.025000  -0.026877
  0.100000  -0.047383
  0.250000  -0.062594
  0.500000  -0.052940
  0.750000  -0.028869
  1.000000  -0.001260
"""

# Lednicer files in the wild often omit the count header.
LEDNICER_NO_HEADER = "\n".join(
    line for line in LEDNICER_TEXT.splitlines() if "7.        7." not in line
)


class TestSeligImport:
    def test_detected_as_selig(self) -> None:
        assert parse_dat(SELIG_TEXT).detected_format == "selig"

    def test_name_is_read_from_the_header(self) -> None:
        assert parse_dat(SELIG_TEXT).name == "NACA 0012 COARSE"

    def test_coordinates_survive_unchanged(self) -> None:
        af = parse_dat(SELIG_TEXT).airfoil
        assert af.n_points == 13
        assert af.x[0] == pytest.approx(1.0)
        assert af.z[0] == pytest.approx(0.001260)
        assert af.x[6] == pytest.approx(0.0)

    def test_ordering_invariant_holds(self) -> None:
        assert parse_dat(SELIG_TEXT).airfoil.signed_area > 0.0

    def test_upper_surface_ends_up_on_top(self) -> None:
        af = parse_dat(SELIG_TEXT).airfoil
        (_, zu), (_, zl) = af.surfaces()
        assert zu.mean() > zl.mean()

    def test_no_count_header_reported(self) -> None:
        assert parse_dat(SELIG_TEXT).had_count_header is False


class TestLednicerImport:
    def test_detected_as_lednicer(self) -> None:
        assert parse_dat(LEDNICER_TEXT).detected_format == "lednicer"

    def test_count_header_is_reported(self) -> None:
        assert parse_dat(LEDNICER_TEXT).had_count_header is True

    def test_detected_without_a_count_header(self) -> None:
        parsed = parse_dat(LEDNICER_NO_HEADER)
        assert parsed.detected_format == "lednicer"
        assert parsed.had_count_header is False

    def test_converts_to_the_same_section_as_the_selig_file(self) -> None:
        """The two fixtures describe the same airfoil, so they must import identically."""
        selig = parse_dat(SELIG_TEXT).airfoil
        lednicer = parse_dat(LEDNICER_TEXT).airfoil
        assert lednicer.n_points == selig.n_points
        assert np.allclose(lednicer.x, selig.x)
        assert np.allclose(lednicer.z, selig.z)

    def test_headerless_variant_agrees_too(self) -> None:
        assert np.allclose(
            parse_dat(LEDNICER_NO_HEADER).airfoil.z, parse_dat(SELIG_TEXT).airfoil.z
        )

    def test_lower_surface_listed_first_is_detected_and_swapped(self) -> None:
        """A file that lists the lower surface first must not import upside down."""
        lines = LEDNICER_NO_HEADER.strip().splitlines()
        name, body = lines[0], [ln for ln in lines[1:] if ln.strip()]
        upper, lower = body[:7], body[7:]
        swapped_text = "\n".join([name, *lower, *upper])

        parsed = parse_dat(swapped_text)
        assert parsed.surfaces_swapped is True
        (_, zu), (_, zl) = parsed.airfoil.surfaces()
        assert zu.mean() > zl.mean()
        assert np.allclose(parsed.airfoil.z, parse_dat(SELIG_TEXT).airfoil.z)


class TestMalformedFiles:
    """Refuse rather than guess."""

    def test_empty_file(self) -> None:
        with pytest.raises(GeometryError, match="at least 7"):
            parse_dat("")

    def test_too_few_points(self) -> None:
        with pytest.raises(GeometryError, match="at least 7"):
            parse_dat("stub\n1.0 0.0\n0.5 0.1\n0.0 0.0\n0.5 -0.1\n")

    def test_text_appearing_after_coordinates(self) -> None:
        with pytest.raises(GeometryError, match="non-numeric line"):
            parse_dat(SELIG_TEXT + "SECOND ELEMENT\n0.0 0.0\n")

    def test_count_header_disagreeing_with_the_data(self) -> None:
        bad = LEDNICER_TEXT.replace("7.        7.", "9.        9.")
        with pytest.raises(GeometryError, match="point-count header says"):
            parse_dat(bad)

    def test_contour_starting_mid_surface(self) -> None:
        """Neither format starts half way along a surface; this must be rejected."""
        af = naca("0012", 61)
        rolled = np.roll(np.column_stack([af.x, af.z]), 12, axis=0)
        text = "rolled\n" + "\n".join(f"{a:.6f} {b:.6f}" for a, b in rolled)
        with pytest.raises(GeometryError):
            parse_dat(text)

    def test_all_points_at_one_station(self) -> None:
        text = "degenerate\n" + "\n".join(f"0.5 {v:.4f}" for v in np.linspace(-1, 1, 9))
        with pytest.raises(GeometryError, match="not an airfoil|identical"):
            parse_dat(text)

    def test_non_finite_coordinate(self) -> None:
        with pytest.raises(GeometryError):
            parse_dat(SELIG_TEXT.replace("0.750000   0.028869", "0.750000   nan"))


class TestParsingDetails:
    def test_comment_and_blank_lines_are_ignored(self) -> None:
        decorated = "# a comment\n\n" + SELIG_TEXT + "\n! trailing comment\n"
        assert parse_dat(decorated).airfoil.n_points == 13

    def test_comma_separated_values(self) -> None:
        commas = SELIG_TEXT.replace("   ", " ").replace(" -", " ,-")
        # only assert it parses; the substitution above is deliberately crude
        assert parse_dat(SELIG_TEXT.replace("0 0", "0, 0")).airfoil.n_points == 13

    def test_missing_name_falls_back(self) -> None:
        body = "\n".join(SELIG_TEXT.splitlines()[1:])
        assert parse_dat(body, name="fallback").name == "fallback"


class TestRoundTrip:
    """Write then read must return the same section, in either format."""

    @pytest.mark.parametrize("fmt", ["selig", "lednicer"])
    @pytest.mark.parametrize("code", ["0012", "2412", "23012"])
    def test_round_trip(self, tmp_path, fmt: str, code: str) -> None:
        original = naca(code, 201)
        path = tmp_path / f"{code}.dat"
        write_dat(original, path, fmt=fmt)
        parsed = read_dat(path)

        assert parsed.detected_format == fmt
        assert parsed.airfoil.n_points == original.n_points
        assert np.allclose(parsed.airfoil.x, original.x, atol=1e-6)
        assert np.allclose(parsed.airfoil.z, original.z, atol=1e-6)

    def test_round_trip_preserves_area_to_writer_precision(self, tmp_path) -> None:
        original = naca("2412", 201)
        path = tmp_path / "a.dat"
        write_dat(original, path)
        assert read_dat(path).airfoil.area == pytest.approx(original.area, rel=1e-5)

    def test_open_trailing_edge_survives(self, tmp_path) -> None:
        original = naca("0012", 201, closed_te=False)
        path = tmp_path / "open.dat"
        write_dat(original, path, fmt="lednicer")
        assert read_dat(path).airfoil.te_gap == pytest.approx(original.te_gap, abs=1e-6)

    def test_name_survives(self, tmp_path) -> None:
        path = tmp_path / "named.dat"
        write_dat(naca("4412", 61, name="my section"), path)
        assert read_dat(path).name == "my section"

    def test_unknown_format_rejected(self, tmp_path) -> None:
        with pytest.raises(GeometryError, match="fmt must be"):
            write_dat(naca("0012", 61), tmp_path / "x.dat", fmt="iges")  # type: ignore[arg-type]

    def test_missing_file_reports_the_path(self, tmp_path) -> None:
        with pytest.raises(GeometryError, match="could not read"):
            read_dat(tmp_path / "nope.dat")
